package io.github.axxiss.places.enums;

/**
 * @author Axxiss
 */
public enum PlaceType {
    Accounting("accounting"),
    Airport("airport"),
    AmusementPark("amusement_park"),
    Aquarium("aquarium"),
    ArtGallery("art_gallery"),
    Atm("atm"),
    Bakery("bakery"),
    Bank("bank"),
    Bar("bar"),
    BeautySalon("beauty_salon"),
    BicycleStore("bicycle_store"),
    BookStore("book_store"),
    BowlingAlley("bowling_alley"),
    BusStation("bus_station"),
    Cafe("cafe"),
    Campground("campground"),
    CarDealer("car_dealer"),
    CarRental("car_rental"),
    CarRepair("car_repair"),
    CarWash("car_wash"),
    Casino("casino"),
    Cemetery("cemetery"),
    Church("church"),
    CityHall("city_hall"),
    Clothing_store("clothing_store"),
    Convenience_store("convenience_store"),
    Courthouse("courthouse"),
    Dentist("dentist"),
    Department_store("department_store"),
    Doctor("doctor"),
    Electrician("electrician"),
    Electronics_store("electronics_store"),
    Embassy("embassy"),
    Establishment("establishment"),
    Finance("finance"),
    FireStation("fire_station"),
    Florist("florist"),
    Food("food"),
    FuneralHome("funeral_home"),
    FurnitureStore("furniture_store"),
    GasStation("gas_station"),
    GeneralContractor("general_contractor"),
    GroceryOrSupermarket("grocery_or_supermarket"),
    Gym("gym"),
    HairCare("hair_care"),
    HardwareStore("hardware_store"),
    Health("health"),
    HinduTemple("hindu_temple"),
    HomeGoodsStore("home_goods_store"),
    Hospital("hospital"),
    InsuranceAgency("insurance_agency"),
    JewelryStore("jewelry_store"),
    Laundry("laundry"),
    Lawyer("lawyer"),
    Library("library"),
    LiquorStore("liquor_store"),
    LocalGovernmentOffice("local_government_office"),
    Locksmith("locksmith"),
    Lodging("lodging"),
    MealDelivery("meal_delivery"),
    MealTakeaway("meal_takeaway"),
    Mosque("mosque"),
    MovieRental("movie_rental"),
    MovieTheater("movie_theater"),
    MovingCompany("moving_company"),
    Museum("museum"),
    NightClub("night_club"),
    Painter("painter"),
    Park("park"),
    Parking("parking"),
    PetStore("pet_store"),
    Pharmacy("pharmacy"),
    Physiotherapist("physiotherapist"),
    PlaceOfWorship("place_of_worship"),
    Plumber("plumber"),
    Police("police"),
    PostOffice("post_office"),
    RealEstateAgency("real_estate_agency"),
    Restaurant("restaurant"),
    RoofingContractor("roofing_contractor"),
    RvPark("rv_park"),
    School("school"),
    ShoeStore("shoe_store"),
    ShoppingMall("shopping_mall"),
    Spa("spa"),
    Stadium("stadium"),
    Storage("storage"),
    Store("store"),
    SubwayStation("subway_station"),
    Synagogue("synagogue"),
    TaxiStand("taxi_stand"),
    TrainStation("train_station"),
    TravelAgency("travel_agency"),
    University("university"),
    VeterinaryCare("veterinary_care"),
    Zoo("zoo");

    String mValue;

    PlaceType(String value) {
        mValue = value;
    }

    public String getValue() {
        return mValue;
    }
}
